=== silSuarezP/SEW-MotoGP/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns="http://www.uniovi.es"
    targetNamespace="http://www.uniovi.es"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="longitudCircuito" />
        <xs:element ref="anchuraMedia" />
        <xs:element ref="carrera" />
        <xs:element ref="ubicacion" />
        <xs:element ref="patrocinador" />
        <xs:element ref="referencias" />
        <xs:element ref="galeriaFotografias" />
        <xs:element ref="galeriaVideos" />
        <xs:element ref="origen" />
        <xs:element ref="tramos" />
        <xs:element ref="resultadoCarrera" />
        <xs:element ref="clasificacionMundial" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="nombre" type="xs:string" />

  <xs:element name="longitudCircuito">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="unidad" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="km"/>
                <xs:enumeration value="m"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="anchuraMedia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="unidad" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="m"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>


  <xs:element name="carrera">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fecha" type="xs:date" />
        <xs:element name="horaInicio" type="xs:time" />
        <xs:element name="vueltas" type="xs:positiveInteger" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="ubicacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="localidad" type="xs:string" />
        <xs:element name="pais">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="España"/>
              <xs:enumeration value="Italia"/>
              <xs:enumeration value="Francia"/>
              <xs:enumeration value="Alemania"/>
              <xs:enumeration value="Portugal"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="patrocinador" type="xs:string" />

  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="referencia" type="xs:string" maxOccurs="3" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="galeriaFotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fotografia" type="xs:string" maxOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="galeriaVideos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="video" type="xs:string" maxOccurs="3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="origen">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="coordenadas" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="longitudGeo" type="xs:decimal"/>
        <xs:element name="latitud" type="xs:decimal"/>
        <xs:element name="altitud" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="tramos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tramo" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="tramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="distancia">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="0.1"/>
              <xs:maxInclusive value="20"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element ref="coordenadas" />
        <xs:element name="sector" type="xs:string" />
      </xs:sequence>
      <xs:attribute name="unidad" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="km"/>
            <xs:enumeration value="m"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>


  <xs:element name="resultadoCarrera">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vencedor" type="xs:string"/>
        <xs:element name="tiempo">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="\d{2}:\d{2}:\d{2}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  
  <xs:element name="clasificacionMundial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="piloto" type="xs:string" maxOccurs="3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== silSuarezP/SEW-MotoGP/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <nombre>Circuit de Barcelona-Catalunya</nombre>
    <longitudCircuito unidad="m">4655</longitudCircuito>
    <anchuraMedia unidad="m">14</anchuraMedia>

    <carrera>
        <fecha>2025-05-03</fecha>
        <horaInicio>14:00</horaInicio>
        <vueltas>66</vueltas>
    </carrera>

    <ubicacion>
        <localidad>Montmeló</localidad>
        <pais>España</pais>
    </ubicacion>

    <patrocinador>Monster Energy</patrocinador>

    <referencias>
        <referencia>https://www.circuitcat.com/</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya</referencia>
        <referencia>https://www.motogp.com/es/circuits/Barcelona-Catalunya</referencia>
    </referencias>

    <galeriaFotografias>
        <fotografia>../multimedia/circuito1.jpg</fotografia>
        <fotografia>../multimedia/circuito2.jpg</fotografia>
        <fotografia>../multimedia/circuito3.jpg</fotografia>
    </galeriaFotografias>

    <galeriaVideos>
        <video>../multimedia/circuito-video.mp4</video>
    </galeriaVideos>

    <origen>
        <coordenadas>
            <longitudGeo>2.2620</longitudGeo>
            <latitud>41.5706</latitud>
            <altitud>90</altitud>
        </coordenadas>
    </origen>

    <tramos>
        <tramo unidad="m">
            <distancia>500</distancia>
            <coordenadas>
                <longitudGeo>2.2630</longitudGeo>
                <latitud>41.5710</latitud>
                <altitud>92</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo unidad="m">
            <distancia>600</distancia>
            <coordenadas>
                <longitudGeo>2.2640</longitudGeo>
                <latitud>41.5720</latitud>
                <altitud>95</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo unidad="m">
            <distancia>700</distancia>
            <coordenadas>
                <longitudGeo>2.2650</longitudGeo>
                <latitud>41.5730</latitud>
                <altitud>97</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
    </tramos>

    <resultadoCarrera>
        <vencedor>Marc Márquez</vencedor>
        <tiempo>1:38:22.345</tiempo>
    </resultadoCarrera>

    <clasificacionMundial>
        <piloto>Fabio Quartararo</piloto>
        <piloto>Francesco Bagnaia</piloto>
        <piloto>Marc Márquez</piloto>
    </clasificacionMundial>
</circuito>
